### ISSUE TITLE
Zero or more parameter does not work correctly for root route in strict mode

### ISSUE THREAD

**Issue by Timer** [pillarjs/path-to-regexp#228] opened 2020-07-08 15:41 UTC
The following code returns false in `strict` mode, likely because it thinks there's a trailing slash:

```js
const p = require('path-to-regexp');
p.match('/:everything*', { strict: true } )('/') => false
```

Is this the intended behavior? It seems strict mode should special case this specific input.

**Comment by blakeembrey** [comment] 2020-07-08 18:50
It is intended behavior. Without this you'd end up with inconsistent behavior, i.e. in Express.js and other apps that support nested routing where it strips the prefix could produce different results at different points. An example:

1. Using two paths of `'/route', { end: false }` then `/:everything*`.
2. Using one path of `/route/:everything*`.

In 1, it would end up matching both `/route` and `/route/` in strict and non-strict. In 2, it would only match `/route` using strict.

It does seem like we could put this behavior behind a flag. Thoughts?

**Comment by blakeembrey** [comment] 2020-07-08 18:52
There's also some apps that use this package in unexpected ways matching non-paths (i.e. `:host.example.com`) and suffix paths (i.e. `foo/bar` without the initial `/`). Implementing this by default might have some unexpected side effects that I haven't considered.

**Comment by Timer** [comment] 2020-07-09 16:37
Could you elaborate more? I'm not sure I fully understand the problem with nested routing and prefix.

Since the matcher has a leading `/`, wouldn't that always force presence of a leading `/`?

```
> p.match('/:everything*', { strict: true } )('abc')
false
```

**Comment by Timer** [comment] 2020-07-10 01:15
How could we write a strict-mode rule that matches `/`, `/abc`, `/abc/def`, etc but not `/abc/`?

I can only think of `/:everything*{/}?` but that permits a trailing slash.

**Comment by blakeembrey** [comment] 2020-07-10 02:28
I’m assuming in this case that `/abc/:everything*` doesn’t match `/abc/`? So it’s specifically a special case for the base `/` of a URL? I’m happy to add this behind a flag because it’s a backward incompatible change.

Why is it backward incompatible? You can create a `/abc` route with `end: false` which trims the suffix. Then a subsequent route could use `/:everything*`. If you give it `/abc` to the first step, it would return `’’`. The next step would match. Using `/abc/` would return `/`, which wouldn’t currently match. Accepting the behavior without a flag would at best accept both, at worst invert the intention of these paths.

I definitely understand that it’s not super clear.

**Comment by Timer** [comment] 2020-07-10 02:44
Correct:

```
> p.match('/abc/:everything*', { strict: true } )('/abc/')
false
```

I can definitely look at making a PR that adds a flag to special case the base of a URL. Any idea what you'd want the flag called?

**Comment by blakeembrey** [comment] 2020-07-10 03:28
No idea right now, but feel free to create the PR first!

**Comment by blakeembrey** [comment] 2020-07-10 04:28
One possibility is passing `root: true` as an option with the match function (instead of the regexp creation) and it would automatically change `'/'` to `''` for you to do the matching?

**Comment by blakeembrey** [comment] 2021-08-08 02:39
I’m going to close this out as-is and recommend people put this into logic wrapping this library. It’d be super easy to do. In my own usages I started using the paths as just `path.slice(1)` since the URLs _always_ start with `/` which could be another way to make this entire case redundant.

**Closed by blakeembrey** 2021-08-08 02:39 UTC
Labels: enhancement
