### ISSUE TITLE
Please provide es module distributable

### ISSUE THREAD

**Issue by jacobg** [pillarjs/path-to-regexp#174] opened 2018-12-06 23:28 UTC
Please provide es module distributable in npm, i.e., instead of:
```
module.exports = pathToRegexp
module.exports.parse = parse
module.exports.compile = compile
module.exports.tokensToFunction = tokensToFunction
module.exports.tokensToRegExp = tokensToRegExp
```

Do this:
```
export default pathToRegexp
pathToRegexp.parse = parse
pathToRegexp.compile = compile
pathToRegexp.tokensToFunction = tokensToFunction
pathToRegexp.tokensToRegExp = tokensToRegExp
```

This is important for webpack applications that have to transpile an ES depedendency that has a transitive dependency on `path-to-regexp`. More on that issue here:

https://github.com/vuejs/vue-cli/issues/1568

**Comment by blakeembrey** [comment] 2018-12-07 00:06
Nothing in that issue lept our to me as requiring this change. Can you specify a specific issue you wish to fix? Webpack definitely works normally with CommonJS and we aren’t going to be moving to ES modules anytime soon since it’s not fully fleshed out under node.js.

**Comment by blakeembrey** [comment] 2018-12-07 02:53
@jacobg What build script would that be? There's isn't one today.

Also, according to the linked article this should also be fine. It's just use-case A1. If you can build a reproduction I will take a look.

**Comment by blikblum** [comment] 2019-06-24 13:19
Hi, just come with a need for this feature not related to webpack at all.

I'm trying to ditch the need to do a build (with rollup) just to test (through karma) a library i develop. Since all code written with ES modules i could just load it, with minimal changes, with current browsers but there's a dependency on path-to-regexp which does not have an es dist

I'm willing to do the work but needs some guidance since it will require some technical decisions.

The more common way would be write the main source code with ES module and run a build step with babel to convert to commonjs

Another way would write a custom build tool (with a few regex) to convert current code to an ES module version.

I can do any of the above

BTW: both can coexist easily with module/main package entries

**Comment by blikblum** [comment] 2019-06-24 15:55
Since was really easy i just did a PR: #190

**Comment by daKmoR** [comment] 2019-08-30 15:26
es modules become more and more important... 🤗 

what would it take to publish it to also support es modules? how about going the same way sinon did?

e.g. in your package.json
```json
"main": "index.js",
"module": "index-es.js",
```

and then the only difference between those files is the export syntax
=> could of course even be automated but not sure if it's worth it

or what do you think is needed for you to support es modules as well?

**Comment by blakeembrey** [comment] 2019-11-11 22:11
This has been worked on in https://github.com/pillarjs/path-to-regexp/pull/203.

**Closed by blakeembrey** 2019-11-11 22:11 UTC
Labels: enhancement
