### ISSUE TITLE
Getting navigation error after upgraded to latest path-to-regexp(8.2.0)

### ISSUE THREAD

**Issue by raviteja74** [pillarjs/path-to-regexp#331] opened 2024-09-26 11:30 UTC
Hello team,
Actually I am new to the javascript world so I need your help on the issue I am facing...the context is I have updated the path-to-regexp from ^6.2.1 to ^8.2.0 after upgrade the below regex in routepath throwing an error like :"Uncaught TypeError: Unexpected at 52,) 
The path I am using is like : "Mypath/:nodePath([^\\s]+)"
Could you please help on any rules need to update the regex to work as like previous?
Thanks in advance 🙂

**Comment by blakeembrey** [comment] 2024-09-26 15:49
Duplicate of https://github.com/pillarjs/path-to-regexp/issues/327. Please read release notes or the README, it’s a major version change so there are breaking changes involved. One of those breaking changes is that capture groups are not supported, so you will need to remove them.

**Closed by blakeembrey** 2024-09-26 15:49 UTC
