### ISSUE TITLE
Impossible to validate a slug

### ISSUE THREAD

**Issue by HelloEdit** [pillarjs/path-to-regexp#205] opened 2019-11-10 15:08 UTC
Hello,

I open this issue because I'm trying for an hour to make this regex work, validating a slug like this https://regexr.com/4ohmg and wich look like this `[a-z0-9]+(?:-[a-z0-9]+)*`.

Now when I try the following code:
```js
let pathToRegexp = require("path-to-regexp")

const regexp = pathToRegexp('/:slug([a-z0-9]+(-[a-z0-9]+)*)')

regexp.exec('/hello-world-this-is-a-valid-slug')
```
The console shows me an undefined output. Am I missing something? 
I hope you can illuminate my lantern 🙏

Thanks,

**Comment by blakeembrey** [comment] 2019-11-10 22:31
There’s no support for nested matching groups in the library.

**Comment by blakeembrey** [comment] 2019-11-11 03:47
Closing as a duplicate of https://github.com/pillarjs/path-to-regexp/issues/95.

**Closed by blakeembrey** 2019-11-11 03:47 UTC

**Comment by blakeembrey** [comment] 2019-11-20 04:09
Just a heads up, but support was added in 4.0 via https://github.com/pillarjs/path-to-regexp/issues/95#issuecomment-552670646. You would need to make the nested group non-capturing with `(?:` though.

**Comment by HelloEdit** [comment] 2019-11-20 15:43
Incredible! Thanks
